version: '3'

services:
  companion-computer:
    container_name: companion-computer
    privileged: true
    build:
      dockerfile: ./companion-computer/Dockerfile
    volumes:
      - companion-computer:/companion-computer

  ground-control-station:
    container_name: ground-control-station
    privileged: true
    build:
      dockerfile: ./ground-control-station/Dockerfile
    volumes:
      - ground-control-station:/ground-control-station
    depends_on:
      - companion-computer

volumes:
  companion-computer:
  ground-control-station: