version: '3'

services:
  flight-controller:
    container_name: flight-controller
    privileged: true
    build:
      dockerfile: ./flight-controller/Dockerfile
    volumes:
      - serial-uart-socket:/sockets
    networks:
      simulator:
        ipv4_address: 10.13.0.2

  companion-computer:
    container_name: companion-computer
    privileged: true
    build:
      dockerfile: ./companion-computer/Dockerfile
    depends_on:
      - flight-controller
    volumes:
      - serial-uart-socket:/sockets
    networks:
      simulator:
        ipv4_address: 10.13.0.3

  ground-control-station:
    container_name: ground-control-station
    privileged: true
    build:
      dockerfile: ./ground-control-station/Dockerfile
    depends_on:
      - companion-computer
    networks:
      simulator:
        ipv4_address: 10.13.0.4

volumes:
  serial-uart-socket:

networks:
  simulator:
    internal: true
    name: simulator
    driver: bridge
    ipam:
      config:
        - subnet: "10.13.0.0/24"