version: '3'

services:
  flight-controller:
    container_name: flight-controller
    privileged: true
    build:
      dockerfile: ./flight-controller/Dockerfile
    volumes:
      - serial-uart-socket:/sockets
    networks:
      simulator:
        ipv4_address: 10.13.0.2

  companion-computer:
    container_name: companion-computer
    privileged: true
    build:
      dockerfile: ./companion-computer/Dockerfile
    depends_on:
      - flight-controller
    volumes:
      - serial-uart-socket:/sockets
    networks:
      simulator:
        ipv4_address: 10.13.0.3

  ground-control-station:
    container_name: ground-control-station
    privileged: true
    build:
      dockerfile: ./ground-control-station/Dockerfile
    depends_on:
      - companion-computer
    networks:
      simulator:
        ipv4_address: 10.13.0.4

  simulator:
    container_name: simulator
    privileged: true
    build:
      dockerfile: ./simulator/Dockerfile
    ports:
      - "8080:8080" # gzweb
      - "8000:8000" # simulator mgmt
    # volumes:
    #   - sim_files:/Simulator
    networks:
      simulator:
        ipv4_address: 10.13.0.5

volumes:
  serial-uart-socket:
  # sim_files:
  ardupilot:

networks:
  simulator:
    name: simulator
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.13.0.0/24"